### ISSUE TITLE
Deploy and Delete shouldn't use GET

### ISSUE THREAD

**Issue by SimonWoolf** [IanVaughan/capo#3]
e.g. if somehow a search engine crawled the page, it'd follow the 'links' and delete everything

per REST, deploy should be a POST to the collection path (eg /deploys), delete should be a DELETE to the element path (eg /deploys/15)

**Comment by IanVaughan** [comment]
You are right, and I had them as that initially.
But I ran into problems when getting the [Hubot (yoda) script][1] to POST to the server, and then follow up with output to Slack. 

When I stabilise the app I'll come back to this and tidy up!

(Keep raising if you see anything!)

[1]:https://github.com/IanVaughan/capo/blob/master/scripts/capo.coffee#L56
